---
metadata:
  - name: description
    content: Blattodea Species File is a database of the published science of the cockroaches and termites of the world, including all extant and fossil taxa.
  - name: keywords
    content: taxonomy, species, distribution, ecology, Species File Group, Cockroaches, Blattodea, Blattoptera, termites, Isoptera, Termitoidae, taxonpages, Blattodea Species File, Cockroach Species File, Isoptera Species File
  - name: robots
    content: follow
