---
metadata:
  - name: description
    content: The Cockroach Species File (CSF) is an up-to-date taxonomic catalogue of the world's cockroaches. Cockroaches belong to the order Blattodea (sometimes known as Blattaria) along with the termites (formerly in a separate order, Isoptera).
  - name: keywords
    content: taxonpages, taxonomy, Cockroach Species File, cockroach species file, sfg, species, Species File Group
  - name: robots
    content: follow
