---
metadata:
  - name: description
    content: Blattodea Species File is a taxanomic database of the cockroaches and termites of the world
  - name: keywords
    content: taxonomy, species, distribution, ecology, Species File Group, Cockroaches, Blattodea, Blattoptera, termites, Isoptera, Termitoidae, taxonpages, Blattodea Species File, Cockroach Species File, Isoptera Species File
  - name: robots
    content: follow
